### ISSUE TITLE
New interface also for SAT?

### ISSUE THREAD

**Issue by zonca** [simonsobs/so_noise_models#5]
I noticed just now that the new class-based 3.1 model is only for LAT.
It would be great if we had the same interface also for SAT, even though nothing changed from 3.0.4.
This way people have a consistent interface to get noise curves both for SAT and LAT.

If you plan to implement this, please give me an ETA (ideally before mid-January), so I can plan accordingly, otherwise I'll implement a mixed interface where I get LAT noise properties from 3.1 and SAT from 3.0.4.

**Comment by jcolinhill** [comment]
@mhasself implemented the very nice re-write for the LAT, so I leave the question up to him...

**Comment by mhasself** [comment]
I should have this ready for review by the end of the day.

**Comment by zonca** [comment]
being implemented in #10
